openapi: 3.0.3
info:
  title: QRAPI - Tenant API
  description: |
    API para operaciones de tenants (empresas). Permite gestionar dispositivos, 
    enviar mensajes por WhatsApp y administrar campa침as.
  version: 1.0.0
  contact:
    name: Soporte QRAPI

servers:
  - url: https://{subdominio}
    description: Servidor del tenant
    variables:
      subdominio:
        default: demo.qr.buho.la
        description: Subdominio espec칤fico del tenant

tags:
  - name: Auth
    description: Autenticaci칩n de usuarios tenant
  - name: Devices
    description: Gesti칩n de dispositivos WhatsApp
  - name: Messages
    description: Env칤o de mensajes por WhatsApp
  - name: Campaigns
    description: Gesti칩n de campa침as de mensajer칤a

security:
  - BearerAuth: []

paths:
  /api/login:
    post:
      tags:
        - Auth
      summary: Login de usuario tenant
      description: Autentica un usuario del tenant y devuelve un token JWT
      security: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - email
                - password
              properties:
                email:
                  type: string
                  format: email
                  example: demo@gmail.com
                password:
                  type: string
                  format: password
                  example: "123456"
      responses:
        '200':
          description: Login exitoso
          content:
            application/json:
              schema:
                type: object
                properties:
                  api_token:
                    type: string
                  user:
                    type: object
        '401':
          description: Credenciales inv치lidas

  /api/verify_token:
    post:
      tags:
        - Auth
      summary: Verificar token JWT
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - api_token
              properties:
                api_token:
                  type: string
      responses:
        '200':
          description: Token v치lido
        '401':
          description: Token inv치lido

  /api/devices/create:
    post:
      tags:
        - Devices
      summary: Crear dispositivo WhatsApp
      description: Registra un nuevo dispositivo para env칤o de mensajes
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DeviceInput'
      responses:
        '201':
          description: Dispositivo creado exitosamente
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Device'
        '422':
          description: Error de validaci칩n

  /api/devices/list:
    get:
      tags:
        - Devices
      summary: Listar dispositivos
      description: Obtiene lista de dispositivos registrados
      responses:
        '200':
          description: Lista de dispositivos
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Device'

  /api/devices/fetch:
    get:
      tags:
        - Devices
      summary: Obtener estado de dispositivos
      description: Recupera informaci칩n actualizada de los dispositivos
      responses:
        '200':
          description: Estado de dispositivos obtenido

  /api/devices/delete/{id}:
    delete:
      tags:
        - Devices
      summary: Eliminar dispositivo
      parameters:
        - name: id
          in: path
          required: true
          description: ID del dispositivo
          schema:
            type: string
      responses:
        '200':
          description: Dispositivo eliminado exitosamente
        '404':
          description: Dispositivo no encontrado

  /api/message/sendText:
    post:
      tags:
        - Messages
      summary: Enviar mensaje de texto
      description: Env칤a un mensaje de texto a un n칰mero de WhatsApp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TextMessage'
            examples:
              ejemplo1:
                summary: Mensaje simple
                value:
                  number: "51929088138"
                  text: "Hola hola"
      responses:
        '200':
          description: Mensaje enviado correctamente
          content:
            application/json:
              schema:
                type: object
                properties:
                  success:
                    type: boolean
                  message:
                    type: string
        '400':
          description: Error en el env칤o
        '401':
          description: No autorizado

  /api/send/{number}:
    post:
      tags:
        - Messages
      summary: Enviar mensaje directo (Gateway)
      description: Env칤a mensaje usando API key sin necesidad de Bearer token
      security:
        - ApiKeyAuth: []
      parameters:
        - name: number
          in: path
          required: true
          description: N칰mero de tel칠fono del dispositivo emisor
          schema:
            type: string
            example: "51987654321"
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/DirectMessage'
      responses:
        '200':
          description: Mensaje enviado exitosamente
        '401':
          description: API key inv치lido

  /api/campaigns/manual:
    post:
      tags:
        - Campaigns
      summary: Crear campa침a manual
      description: Crea una campa침a de mensajer칤a dirigida a grupos espec칤ficos
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ManualCampaign'
      responses:
        '201':
          description: Campa침a creada exitosamente
        '422':
          description: Error de validaci칩n

  /api/campaigns/list:
    get:
      tags:
        - Campaigns
      summary: Listar campa침as
      description: Obtiene lista de campa침as creadas
      responses:
        '200':
          description: Lista de campa침as
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Campaign'

  /api/campaigns/show/{id}:
    get:
      tags:
        - Campaigns
      summary: Detalles de campa침a
      description: Obtiene informaci칩n detallada de una campa침a espec칤fica
      parameters:
        - name: id
          in: path
          required: true
          description: ID de la campa침a
          schema:
            type: integer
      responses:
        '200':
          description: Detalles de la campa침a
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Campaign'
        '404':
          description: Campa침a no encontrada

components:
  securitySchemes:
    BearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
      description: Token JWT obtenido del login

    ApiKeyAuth:
      type: apiKey
      in: header
      name: apikey
      description: API key para env칤o directo de mensajes

  schemas:
    Device:
      type: object
      properties:
        id:
          type: string
        name:
          type: string
        phone:
          type: string
        status:
          type: string
          enum: [active, inactive, disconnected]
        created_at:
          type: string
          format: date-time

    DeviceInput:
      type: object
      required:
        - name
        - phone
      properties:
        name:
          type: string
          example: Mi Dispositivo
          description: Nombre identificador del dispositivo
        phone:
          type: string
          example: "51987654321"
          description: N칰mero de tel칠fono en formato internacional sin el +

    TextMessage:
      type: object
      required:
        - number
        - text
      properties:
        number:
          type: string
          example: "51929088138"
          description: N칰mero de destino en formato internacional sin el +
        text:
          type: string
          example: Hola hola
          description: Mensaje de texto a enviar

    DirectMessage:
      type: object
      required:
        - type
        - payload
      properties:
        type:
          type: string
          enum: [sendText, sendImage, sendDocument, sendAudio]
          example: sendText
        payload:
          type: object
          properties:
            number:
              type: string
              example: "51929088138"
            text:
              type: string
              example: Hola desde el gateway 游녦
      example:
        type: sendText
        payload:
          number: "51929088138"
          text: "Hola desde el gateway 游녦"

    ManualCampaign:
      type: object
      required:
        - title
        - groups
        - message
      properties:
        title:
          type: string
          example: Campa침a de prueba
        groups:
          type: array
          items:
            type: integer
          example: [1, 2]
          description: IDs de los grupos destinatarios
        message:
          type: string
          example: Hola, este es un mensaje de prueba.
        schedule_at:
          type: string
          format: date-time
          example: "2025-10-01 10:00:00"
          description: Fecha y hora de env칤o programado (opcional)
        attach_pdf:
          type: string
          nullable: true
          description: URL o path del PDF adjunto (opcional)

    Campaign:
      type: object
      properties:
        id:
          type: integer
        title:
          type: string
        status:
          type: string
          enum: [pending, processing, completed, failed]
        total_recipients:
          type: integer
        sent_count:
          type: integer
        failed_count:
          type: integer
        schedule_at:
          type: string
          format: date-time
        created_at:
          type: string
          format: date-time

x-code-samples:
  - lang: javascript
    label: JavaScript (Node.js)
    source: |
      const client = new HttpClient();
      const request = new HttpRequestMessage(HttpMethod.Post, "https://demo.qr.uio.la/api/message/send-text");
      const content = new StringContent("{\n  \"number\": \"123456789\",\n  \"message\": \"Plain text message\"\n}");
      request.Headers.Add("Accept", "application/json");
      request.Content = content;
      const response = await client.SendAsync(request);
      response.EnsureSuccessStatusCode();
      Console.WriteLine(await response.Content.ReadAsStringAsync());

  - lang: php
    label: PHP
    source: |
      <?php
      $curl = curl_init();
      curl_setopt_array($curl, [
        CURLOPT_URL => "https://demo.qr.uio.la/api/message/send-text",
        CURLOPT_RETURNTRANSFER => true,
        CURLOPT_POST => true,
        CURLOPT_HTTPHEADER => [
          "Accept: application/json",
          "Authorization: Bearer YOUR_TOKEN"
        ],
        CURLOPT_POSTFIELDS => json_encode([
          "number" => "51929088138",
          "text" => "Hola desde PHP"
        ])
      ]);
      $response = curl_exec($curl);
      curl_close($curl);
      echo $response;

  - lang: python
    label: Python
    source: |
      import requests
      
      url = "https://demo.qr.uio.la/api/message/sendText"
      headers = {
          "Accept": "application/json",
          "Authorization": "Bearer YOUR_TOKEN"
      }
      data = {
          "number": "51929088138",
          "text": "Hola desde Python"
      }
      
      response = requests.post(url, json=data, headers=headers)
      print(response.json())